In [2]:
import numpy as np
from sklearn.datasets import load_diabetes

In [3]:
X,y= load_diabetes(return_X_y=True)

In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [5]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
X.shape

(442, 10)

In [7]:
y.shape

(442,)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=48)

In [9]:
X_train.shape

(353, 10)

In [10]:
y_train.shape

(353,)

In [11]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [12]:
lr.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = lr.predict(X_test)

In [30]:
y_pred

array([ 71.9235596 ,  86.71143741, 109.59800614, 253.47704925,
       218.3391544 , 110.50567183, 154.14258968, 109.27894661,
       176.2493745 , 134.83746092, 104.4662564 , 184.70419276,
       192.15344246, 220.91170834, 184.98453337, 183.45615472,
       204.18734103, 206.62498292, 209.38042909, 169.40022397,
        65.53974048, 149.91338053,  41.65215377,  52.65438687,
       188.69563739, 212.47286501,  54.71477426, 148.30424967,
       201.71210745, 223.32745665, 208.62466511, 151.94168287,
       163.89793863, 169.65258335, 207.37644416,  90.27028361,
       150.93281516, 121.35655225, 191.90840597, 109.93065743,
        50.84096266, 143.53633102,  85.87620034, 163.90745505,
       222.70826004, 153.59342207, 124.79640581, 167.70329522,
       120.12307872, 190.45458729, 212.65934268, 101.78859675,
        88.46948065, 109.61768396,  54.15884652, 194.44293908,
       147.49558177, 126.57282585, 156.5482368 ,  78.8686301 ,
       147.18118232, 248.31675458, 186.17195254, 189.27

In [14]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5639138729762289

In [15]:
lr.coef_

array([  24.74412593, -234.99917259,  508.83304768,  313.71484428,
       -926.24753406,  556.81923022,  181.81411127,  235.01027595,
        778.60219675,   59.79908522])

In [16]:
lr.intercept_

149.84245859442606

# Linear Regression without Scikit learn

In [27]:
class LinearReg:

  def __init__(self):
    self.coef_ = None
    self.intercept_ = None

  # we need to find beta values
  def fit(self, X_train, y_train):

    X_train = np.insert(X_train, 0, 1, axis=1)  # adding extra 1 column in the matrix
    
    
    # calculate the beta coef.
    betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)

    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict(self, X_test):
    
    # y = X.dot(coef_)

    y_pred = np.dot(X_test, self.coef_) + self.intercept_

    return y_pred


In [32]:
lin_reg = LinearReg()

In [33]:
lin_reg.fit(X_train, y_train)

In [34]:
lin_reg.predict(X_test)

array([ 71.9235596 ,  86.71143741, 109.59800614, 253.47704925,
       218.3391544 , 110.50567183, 154.14258968, 109.27894661,
       176.2493745 , 134.83746092, 104.4662564 , 184.70419276,
       192.15344246, 220.91170834, 184.98453337, 183.45615472,
       204.18734103, 206.62498292, 209.38042909, 169.40022397,
        65.53974048, 149.91338053,  41.65215377,  52.65438687,
       188.69563739, 212.47286501,  54.71477426, 148.30424967,
       201.71210745, 223.32745665, 208.62466511, 151.94168287,
       163.89793863, 169.65258335, 207.37644416,  90.27028361,
       150.93281516, 121.35655225, 191.90840597, 109.93065743,
        50.84096266, 143.53633102,  85.87620034, 163.90745505,
       222.70826004, 153.59342207, 124.79640581, 167.70329522,
       120.12307872, 190.45458729, 212.65934268, 101.78859675,
        88.46948065, 109.61768396,  54.15884652, 194.44293908,
       147.49558177, 126.57282585, 156.5482368 ,  78.8686301 ,
       147.18118232, 248.31675458, 186.17195254, 189.27

In [35]:
lin_reg.coef_

array([  24.74412593, -234.99917259,  508.83304768,  313.71484428,
       -926.24753406,  556.81923022,  181.81411127,  235.01027595,
        778.60219675,   59.79908522])

In [36]:
lin_reg.intercept_

149.84245859442612